services:
  - type: web
    name: yoyoxcloud-telegram-bot
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: >-
      bash -c 'export TELEGRAM_BOT_TOKEN=8542557681:AAF42OpFf2nHY4Rl6l0jkjRUDI9wb-DAcus &&
      export ADMIN_USERNAME=AraboMardelli &&
      export ADMIN_PASSWORD=AraboKing336 &&
      python main.py'
