services:
  - type: web
    name: yoyoxcloud-telegram-bot
    env: python
    plan: free
    
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: 8542557681:AAF42OpFf2nHY4Rl6l0jkjRUDI9wb-DAcus
      - key: ADMIN_USERNAME
        value: AraboMardelli
      - key: ADMIN_PASSWORD
        value: AraboKing336
